substitutions:

  friendly_name: "Shelf Sensors"

esphome:
  name: shelfsensors

esp8266:
  board: d1_mini

packages:
  wifi: !include common/wifi.yaml
  default: !include common/default.yaml
  diag: !include common/diag.yaml

logger:
  level: INFO
  logs:
    display.component: ERROR

api:
  encryption:
    key: "S/9TR3qvT4iWEhcArUTYc+N9VMWaRdR+eeKpmnVpcWs="

ota:
  platform: esphome
  password: "49ce935336c03777452d84d3dacab63d"

wifi:
  manual_ip: 
    static_ip: !secret shelfsensors_ip

#remote_receiver:
#   pin:
#    number: D5
#    inverted: true
#   dump: lg

remote_transmitter:
   pin: D6
   carrier_duty_percent: 50%
    
binary_sensor:
  - platform: gpio
    pin: D8
    name: "Living Room Motion Sensor"
    device_class: motion
    icon: mdi:motion-sensor

sensor:
  - platform: dht
    model: DHT22
    pin: D2
    temperature:
      name: "${friendly_name} Temperature"
      icon: mdi:thermometer
      filters:
      - offset: -4.0
    humidity:
      name: "${friendly_name} Humidity"
      icon: mdi:air-filter
    update_interval: 60s

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D7
    num_leds: 1
    name: "${friendly_name} Light"
    icon: mdi:lightbulb
    id: shelfsensor_light
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - light.control:
            id: shelfsensor_light
            effect: Rainbow Effect wide
            brightness: 60%
            
    effects:
      - flicker:
      - flicker:
          name: Flicker Effect With Custom Values
          alpha: 95%
          intensity: 1.5%    
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - random:
      - random:
          name: Random Effect With Custom Values
          transition_length: 10s
          update_interval: 7s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect slow
          speed: 20
          width: 10
      - addressable_rainbow:
          name: Rainbow Effect wide
          speed: 1
          width: 200

button:
  - platform: template
    name: "TV Turn Off"
    icon: mdi:television-classic
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0C

  - platform: template
    name: "TV Mute"
    icon: mdi:volume-mute
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0C

  - platform: template
    name: "TV Volume Up"
    icon: mdi:volume-plus
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x15
        repeat:
         times: 2
         wait_time: 50ms

  - platform: template
    name: "TV Volume Down"
    icon: mdi:volume-minus
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x14

  - platform: template
    name: "TV Volume OK"
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x26
     
  - platform: template
    name: "Vape Power"
    icon: mdi:cannabis
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE7887
        nbits: 32
        
  - platform: template
    name: "Fan1"
    icon: mdi:fan
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE20DF
        nbits: 32
        
  - platform: template
    name: "Fan2"
    icon: mdi:fan
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FEA05F
        nbits: 32
        
  - platform: template
    name: "Fan3"
    icon: mdi:fan
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE609F
        nbits: 32
        
  - platform: template
    name: "Fan Off"
    icon: mdi:fan-off
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE10EF
        nbits: 32
        
  - platform: template
    name: "Temp Up"
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FED827
        nbits: 32
        
  - platform: template
    name: "Temp Down"
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FEB04F
        nbits: 32
        
  - platform: template
    name: "Temp 200"
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE50AF
        nbits: 32
        
  - platform: template
    name: "Temp 210"
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FEF807
        nbits: 32
        
  - platform: template
    name: "Temp 220"
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE30CF
        nbits: 32    
       
  - platform: template
    name: "Temp 230"
    on_press:
      remote_transmitter.transmit_lg:
        data: 0x01FE708F
        nbits: 32 
